version: "3"

services:
  rest-api:
    container_name: rest-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: development
      SERVER_PORT: 3000
