version: "3"

services:
  auth-service:
    container_name: auth-service-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - auth-db
    environment:
      NODE_ENV: development
      POSTGRES_HOST: auth-db-dev
    env_file:
      .db.env

  auth-db:
    container_name: auth-db-dev
    image: postgres:11-alpine
    volumes:
      - auth-data-dev:/var/lib/postgresql/data
    env_file:
      - .db.env

volumes:
  auth-data-dev:
    external: true
