version: "3"

services:
  auth-service:
    container_name: auth-service-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - auth-db
    environment:
      NODE_ENV: development
      POSTGRES_HOST: auth-db-dev
      CONSUL_HOST: consul-dev
      GRPC_PORT: 3000
    networks:
      - ig-clone-dev
    env_file:
      - .db.env
      - .auth.env

  auth-db:
    container_name: auth-db-dev
    image: postgres:11-alpine
    volumes:
      - auth-data-dev:/var/lib/postgresql/data
    networks:
      - ig-clone-dev
    env_file:
      - .db.env

networks:
  ig-clone-dev:
    external:
      name: ig-clone-dev

volumes:
  auth-data-dev:
    external: true
